using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;


namespace godTierCapstoneASP.Models
{
    public class PostModel
    {
        public PostModel()
        {
            status = PostStatus.Open;
            details = null;
        }

        /// <summary>
        /// the id of the post. Identity element generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        /// <summary>
        /// The text contained in the post. Typed by the user
        /// </summary>
        [Required]
        public string details { get; set; }

        /// <summary>
        /// The PostStatus (open, accepted, completed, expired or deleted.
        /// </summary>
        public int status { get; set; }

        /// <summary>
        /// Latitude of the original location (pickup point)
        /// </summary>
        [Required]
        public decimal? originLat { get; set; }

        /// <summary>
        /// longitude of the origin location (pickup point)
        /// </summary>
        [Required]
        public decimal? originLong { get; set; }

        /// <summary>
        /// latitude of destination location (delivery location)
        /// </summary>
        [Required]
        public decimal? destinationLat { get; set; }

        /// <summary>
        /// longitude of destination location (Delivery location)
        /// </summary>
        [Required]
        public decimal? destinationLong { get; set; }


        /// <summary>
        /// The user id of the user who created the post.
        /// </summary>
        public int createdBy { get; set; }

        /// <summary>
        /// The user id of the user who accepted the post. can be null
        /// </summary>
        public int? acceptedBy { get; set; }

        /// <summary>
        /// The user id of the user who is delivering or delivered the post. can be null
        /// </summary>
        public int? deliveredBy { get; set; }

        /// <summary>
        /// The time at which post was created. computed by the database upon creation, never modified
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime createdOn { get; set; }

        /// <summary>
        /// the date time value of when the post was last modified. auto generated by the database everytime anything is changed for the post.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime lastModified { get; set; }

        /// <summary>
        /// The user who created the post
        /// </summary>
        [ForeignKey("createdBy")]
        public CustomLoginModel createdByUser { get; set; }

        /// <summary>
        /// The user who accepted the post
        /// </summary>
        [ForeignKey("acceptedBy")]
        public CustomLoginModel acceptedByUser { get; set; }

        /// <summary>
        /// The user who is delivering or has delivered the post
        /// </summary>
        [ForeignKey("deliveredBy")]
        public CustomLoginModel deliveredByUser { get; set; }
    }

    public class PostContext : DbContext
    {
        public DbSet<PostModel> Posts { get; set; }
        public PostContext(DbContextOptions<PostContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PostModel>().HasKey(p => p.id);
            modelBuilder.Entity<PostModel>().ToTable("Posts");
        }
    }

    public class PostStatus
    {
        public static readonly int Open = 0;
        public static readonly int Accepted = 1;
        public static readonly int Completed = 2;
        public static readonly int Expired = 3;
        public static readonly int Deleted = 4;
    }
}
